FROM node:24-alpine AS dependencies

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

FROM dependencies AS development

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]

FROM dependencies AS build

ARG VITE_API_URL
ARG VITE_DEMO_USERS_PASSWORD
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_DEMO_USERS_PASSWORD=$VITE_DEMO_USERS_PASSWORD

COPY . .
RUN npm run build

FROM nginx:1.28-alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
